version: '3.7'

services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=redis
      - DB_PORT=6379
      - WEB_SERVER_PORT=8080
      - IP_RATE_LIMIT=10
      - IP_RATE_INTERVAL=1
      - IP_BLOCK_TIME=60
      - DEFAULT_TOKEN_RATE_LIMIT=30
      - DEFAULT_TOKEN_RATE_INTERVAL=30
      - TOKEN_BLOCK_TIME=60
      - TOKENS=ABC123:10/1,DEF456:20/2
    depends_on:
      - redis

